# Generated by Django 3.0.7 on 2020-06-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('image', models.ImageField(blank=True, upload_to='shop/', verbose_name='Изображения')),
                ('description', models.TextField(verbose_name='Описание')),
                ('pub_date', models.DateTimeField(default='', verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
